### ISSUE TITLE
Close keyboard when user presses the designated button

### ISSUE THREAD

**Issue by Vaweila** [ionic-selectable/ionic-selectable#123]
Hey,

I've come across a problem with the keyboard interaction in your component.

When a user enters a searchterm and the searchresult contains more entries than the screen can show, they will be correctly shown below. But there is no possibility to close the keyboard on the device by using any key on the keyboard, as it's expected by some users.

On Android, users can at least use the 'back'-button to close the keyboard and then look at the lower items more easily, or scroll down while the keyboard is visible or even click on the title at the upper region of the screen to close the keyboard.

On iOS the user can only close his keyboard by pressing on the title at the upper region of the screen. Further, it also seems that the user can't scroll down the list, as iOS thinks that the area behind the keyboard is still visible and won't scroll further downwards.

Clicking on an item in the list is also no option for users who want to pick an option from further below, as this would select the clicked entry and close the selectable right afterwards.

Is there any solution to this? If not, I'd like to propose that..

..the iOS keyboard shows the 'Search'-button (maybe even with the customized searchButtonText), which it doesn't do yet, it only shows 'Return'. Upon clicking that button, the keyboard should close and the searchBar should lose focus. Maybe there could even be the functionality that searching will only happen that way and not with the debounce.

For Android the same thing should apply, but Android already has a 'Search'-Icon in place.

For reference, thats how it looks like as of now:
Example-Android: http://i.stack.imgur.com/sibZT.jpg
Example-iOS: http://www.globalnerdy.com/wordpress/wp-content/uploads/2015/05/dismissing-ios-keyboard-with-return-key.jpg

Thanks in advance,
Vaweila

**Comment by Vaweila** [comment]
Just adding in my systems information here:

cli packages: (C:\Users\anonym\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
local packages:
    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.1.4 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2
System:
    Node : v8.11.4
    npm  : 5.6.0
    OS   : Windows 10
Environment Variables:
    ANDROID_HOME : not set
Misc:
    backend : pro

I'm using "ionic-selectable": "^3.0.3" of your plugin since we are still developing with Ionic 3.

Greetings

**Comment by Vaweila** [comment]
Hey there,
any update on this?

Do you think it would be feasable to implement something to customize the keyboard when searching for things?

Do you think you'll implement it or do you recommend doing it myself and creating a pull request afterwards?

Thanks

**Comment by edy-ap** [comment]
thansk for you contribution, Can you provide more information, such as versions, code pieces, images?
