### ISSUE TITLE
When no item is found with virtual scroll enabled, the items don't reappear upon clearing input

### ISSUE THREAD

**Issue by rodrake1** [ionic-selectable/ionic-selectable#146]
When the typed text has no matches and the `searchFailText` appears, there's no way of showing the array of items back again after clearing the searched text.

**Comment by eakoriakin** [comment]
It works fine in the demo:
https://stackblitz.com/edit/ionic-selectable-adding-on-search-fail?file=app/pages/home/home.html

**Comment by rodrake1** [comment]
Yes, it does, but when you enable `hasVirtualScroll` it doesn't work anymore.

**Comment by eakoriakin** [comment]
I see, okay, I'll take a look

**Comment by ruisilva450** [comment]
Sorry to bother but do you have any news on this?

**Comment by zhanglongchina** [comment]
still have the problem in version 3.4

**Comment by yurik94** [comment]
Any news?

**Comment by edy-ap** [comment]
Hello! Does this incident still occur?

**Comment by edy-ap** [comment]
You can use header template for customize the search bar, toggle "canSearch" to false, and in header template include your own search bar, you must implement logic filter, an use this methods:

https://github.com/eakoriakin/ionic-selectable/wiki#startsearch
https://github.com/eakoriakin/ionic-selectable/wiki#endsearch
