### ISSUE TITLE
Search template to override default Searchbar

### ISSUE THREAD

**Issue by eakoriakin** [ionic-selectable/ionic-selectable#186]

**Comment by maxfloden** [comment]
I would like to change the search bar icon, i think a search template would allow me to do this. Or is it already possible in some other way?

**Comment by Monomachus** [comment]
👍

**Comment by edy-ap** [comment]
You can use header template for customize the search bar, toggle "canSearch" to false, and in header template include your own search bar, you must implement logic filter, an use this methods:

https://github.com/eakoriakin/ionic-selectable/wiki#startsearch
https://github.com/eakoriakin/ionic-selectable/wiki#endsearch
