### ISSUE TITLE
Enable background dismiss

### ISSUE THREAD

**Issue by schagani** [ionic-selectable/ionic-selectable#202]
Hi All:

I am trying to disable background dismiss but unable to find out the option. I tried the option given on the below link but unable to resolve.

https://github.com/eakoriakin/ionic-selectable/wiki#shouldBackdropClose

Any suggestion.

Regards

**Comment by edy-ap** [comment]
Then you can show the piece of code?

**Comment by edy-ap** [comment]
it will solved in Ionic Selectable v5(currently in alpha)
@ionic-selectable/core for Vanilla JS
@ionic-selectable/angular for Angular
