### ISSUE TITLE
Directive IonicSelectableModalComponent

### ISSUE THREAD

**Issue by m4riachi** [ionic-selectable/ionic-selectable#210]
I get this error when i want to build the apk on ionic 4
> ERROR in (1,1): : Directive IonicSelectableModalComponent, Expected 0 arguments, but got 1.
node_modules/ionic-selectable/ionic-selectable.d.ts.IonicSelectableModalComponent.html(122,5): : Expected 0 arguments, but got 1.

**Comment by edy-ap** [comment]
can you show the versions of angular on package json?

**Comment by edy-ap** [comment]
some answer?
