### ISSUE TITLE
When the keyboard is invoked for the search box on Android, and iOS, the modal goes to full screen.

### ISSUE THREAD

**Issue by pjc2007** [ionic-selectable/ionic-selectable#224]
When I open the select, the modal displayed in a modal window as expected. However, when I tap into the search box, the modal goes to **full screen**.

This only happens on iOS and Android, but not when I am running using IOnic serve in the browser, or when I build UWP and run on a  Windows tablet or Windows desktop

**Comment by edy-ap** [comment]
Can you upload a code example or image?

**Comment by pjc2007** [comment]
@edy-ap no problems. So running on an Android tablet and inspecting, here is this component before entering the search..

![image](https://user-images.githubusercontent.com/10663978/71455154-cd570580-27ce-11ea-8e8c-e5df08f498eb.png)

Perfect.

Now, I tap in the search, and I see the following...

![image](https://user-images.githubusercontent.com/10663978/71455200-f8415980-27ce-11ea-87f7-b6dcd111f942.png)

I can see what is causing this. If we look at the styles without tapping in the search, we have the following..

![image](https://user-images.githubusercontent.com/10663978/71455371-a0572280-27cf-11ea-8332-50554efc2c50.png)

So the media query is setting height/width to 600px.

But when we tap the search, we have the following...

![image](https://user-images.githubusercontent.com/10663978/71455435-fcba4200-27cf-11ea-97bd-b85332663b61.png)

Just setting these to `600px` however is not quite enough, we no need room for the keyboard. If I do this the search input is hidden.

I do use some media queries myself and ionic alert styling, but I don't think the above are mine?

let me know if anything else I can assist with for this.

**Comment by pjc2007** [comment]
I have a work around that seems to be working for the moment..

I define my own class and define a similar media query but leave out the height and just target the width...

```
@media screen and (min-width: 768px) {
    .my-ionic-selectable {
      --width: 600px;
    }
  }
```

And then pass this to the component...

```
<ionic-selectable modalCssClass='my-ionic-selectable'
```

Works in both orientations for the larger 10.5 screen Android tablet. Will need to test with smaller screen tablets.
