### ISSUE TITLE
Ionic 5 when used within a modal selecting an item closes the modal on Android

### ISSUE THREAD

**Issue by webfletch** [ionic-selectable/ionic-selectable#254]
I have updated my Ionic 3 App to Ionic 5 and there seems to be an issue with ionic-selectable when used within a modal page, it seems that when you select an item from the ionic-selectable list as well as closing the ionic-selectable page/window it also closes (or it seems, partially closes) the modal window behind.

I say partially closes because if you click around on the page afterwards it is as if the modal page is still there because you can do things such as bring back up the ionic-selectable page or click into input fields (i.e. the keyboard shows but you can't see the field).

It is almost as if the command that closes the ionic-selectable modal is also closing the modal you called it from (or at least making it invisible).

This is only happening on Android devices and emulators, it works fine when testing in a web browser and on an iOS device.

I am running ionic-selectable 4.6.0

I have uploaded a video showing an example here, you will be able to see that when I select an item from the ionic-selectable list, the "Edit part" modal window closes as well, yet I can still seem to click the fields within it even though they are not visible: https://streamable.com/8vwbi

**Comment by edn9** [comment]
Up.
I have the same issue, a way to workaround is to not use the page in modal but with `router.navigate()`. Looks like when the button click to close, the action affect all the opened modals.

I am running: `"ionic-selectable": "^4.4.0"`.

**Comment by webfletch** [comment]
Yes, I thought that changing to not use a modal would be a workaround but would prefer to use modals if possible especially as I was thinking of taking advantage of the new modal options (slide to close) for iOS in Ionic 5.

**Comment by webfletch** [comment]
Also what device/emulator and Android version are you testing on?
I have a physical Samsung Galaxy S8 that had the problem on Android 8, I have upgraded to Android 9 on this device and the problem seems to have gone, however if I test in an emulator then the problem happens on Android 8, 9 and 10. Very strange!

**Comment by ARHANIZAR** [comment]
Actually It's a problem related to Ionic Modals generally.
@webfletch @edn9 you can try this build to resolve this issue `npm i @ionic/angular@5.1.0-dev.202004011618.3123a31`.
For more details about this issue read : https://github.com/ionic-team/ionic-framework/issues/20610
Hope It will help you!
