### ISSUE TITLE
Floating ion-label and placeholder

### ISSUE THREAD

**Issue by kunajs** [ionic-selectable/ionic-selectable#276]
If I use 
`<ion-label floating>Port</ion-label>`
together with 
`<ionic-selectable placeholder="select...">...</ionic-selectable>`
the text overlaps each other.

example here: https://stackblitz.com/edit/ionic-selectable-labels-amxcda
in comparison with classic ion-selectable: https://stackblitz.com/edit/ionic-v4-ltw9nj

Any chance there is going to be support for this?

**Comment by edy-ap** [comment]
can you give the version, please? thanks for use ionic-selectable

**Comment by kunajs** [comment]
Hi,
thanks for reply.

Stackblitz example uses 
```
"ionic-angular": "3.9.2",
"ionic-selectable": "3.4.0",
```
but the same behavior is also detected with these versions:
```
"@ionic/angular": "^5.0.5",
"ionic-selectable": "^4.7.1",
```

**Comment by kunajs** [comment]
Hi,
so what is the current status of this?

**Comment by edy-ap** [comment]
it will be fixed in v5

**Comment by kunajs** [comment]
Hi, thanks. When do you plan to release v5?

**Comment by edy-ap** [comment]
You can use header template for customize the search bar, toggle "canSearch" to false, and in header template include your own search bar, you must implement logic filter, an use this methods:

https://github.com/eakoriakin/ionic-selectable/wiki#startsearch
https://github.com/eakoriakin/ionic-selectable/wiki#endsearch
