### ISSUE TITLE
React guide

### ISSUE THREAD

**Issue by pascalchristian** [ionic-selectable/ionic-selectable#290]
Hi, is there a guide to use this module with React? Or even with basic javascript? Not familiar with Angular.

**Comment by edy-ap** [comment]
Hi, for the moment we not support react, maybe in future versions.

**Comment by Path-A** [comment]
I'd like to chime in and also ask for Ionic-Vue support!

**Comment by edy-ap** [comment]
Ionic Selectable v5(currently in alpha)
@ionic-selectable/core for Vanilla JS
@ionic-selectable/angular for Angular

**Comment by AntoineDannemark** [comment]
Hi, 
Your readme mentions support for other frameworks coming.. Any chance soon with React? 
Thx!
