### ISSUE TITLE
Styling the ion-searchbar

### ISSUE THREAD

**Issue by ignacio-vivot** [ionic-selectable/ionic-selectable#291]
I'm using Ionic 3. 
I can't find a way to style (css) the modal searchbar. Is this posible?

**Comment by edy-ap** [comment]
hi!, you solved the problem?

**Comment by ignacio-vivot** [comment]
After some try and error I was able to find the correct css selectors to target the searchbar.
    .searchbar-input {
        background: #FFF !important;
        color: #000 !important;
    }
    .searchbar-input::placeholder {
        color: #2d2d2d;
    }

**Comment by rzi9i** [comment]
Hi! i try to use the solution given by @ignacio-vivot but no effect, there is any other solution ?
I'm using latest version of Ionic.

**Comment by faisal-easi** [comment]
has anyone changed the color , same problem is with me

**Comment by edy-ap** [comment]
You can use header template for customize the search bar, toggle "canSearch" to false, and in header template include your own search bar, you must implement logic filter, an use this methods:

https://github.com/eakoriakin/ionic-selectable/wiki#startsearch
https://github.com/eakoriakin/ionic-selectable/wiki#endsearch
