### ISSUE TITLE
onSerach not fire  v4.6.0

### ISSUE THREAD

**Issue by surendra-17** [ionic-selectable/ionic-selectable#300]
<ionic-selectable
                            #locComponent
                            closeButtonSlot="end"
                            formControlName="location"
                            [items]="locationList"
                            itemValueField="id"
                            itemTextField="name"
                            [shouldStoreItemValue]="true"
                            [shouldFocusSearchbar]="true"
                            [canSearch]="true"
                            (onSerach)="searchLocations($event)">
                      </ionic-selectable>

  searchLocations(event: {
    component: IonicSelectableComponent,
    text: string
  }) {
    console.log('on serach call',event);
    let text = event.text.trim().toLowerCase();
    event.component.startSearch();

    // Close any running subscription.
    if (this.locationSubscription) {
      this.locationSubscription.unsubscribe();
    }

    if (!text) {
      // Close any running subscription.
      if (this.locationSubscription) {
        this.locationSubscription.unsubscribe();
      }

      event.component.items = [];
      event.component.endSearch();
      return;
    }

    this.locationSubscription = this._apiListingService.getpreferredLocation(text).subscribe(locations => {
      // Subscription will be closed when unsubscribed manually.
      if (this.locationSubscription.closed) {
        return;
      }

      event.component.items = locations;
      event.component.endSearch();
    });

  }

"dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/core": "^1.4.0",
    "@capacitor/ios": "^1.4.0",
    "@ionic-native/core": "^5.19.1",
    "@ionic-native/file": "^5.19.1",
    "@ionic-native/http": "^5.19.1",
    "@ionic-native/printer": "^5.19.1",
    "@ionic/angular": "^4.11.8",
    "angular2-signaturepad": "^2.11.0",
    "cordova-android": "8.1.0",
    "cordova-ios": "5.1.1",
    "cordova-plugin-advanced-http": "^2.3.1",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-printer": "^0.8.0",
    "cordova-plugin-whitelist": "^1.3.4",
    "core-js": "^2.6.11",
    "ionic-selectable": "^4.6.0",
    "ionicsignaturepad": "^1.0.1",
    "ng-otp-input": "^1.7.1",
    "rxjs": "^6.5.4",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },

**Comment by edy-ap** [comment]
it will solved in Ionic Selectable v5(currently in alpha)
@ionic-selectable/core for Vanilla JS
@ionic-selectable/angular for Angular
