### ISSUE TITLE
Styiling of ionic-selectable header

### ISSUE THREAD

**Issue by serridavide** [ionic-selectable/ionic-selectable#317]
Hello, I am new to this component, I implemented it successfully into my ionic application but i run into an issue. I am not able to style the header of the component. No matter what I try it will always display the default toolbar and searchbar color set up as main style in the application. Unfortunately my application is very large so I am unable to define 1 styling for all the toolbars in the whole application and I'm in desperate need to be able to change it.

I am using Ionic 5 and Angular 9 as of today.

**Comment by edy-ap** [comment]
You can use https://github.com/eakoriakin/ionic-selectable/wiki#headercolor
or https://github.com/eakoriakin/ionic-selectable/wiki#header-template

You can find more documentation at https://github.com/eakoriakin/ionic-selectable/wiki

**Comment by serridavide** [comment]
I completely missed it on the documentation! thanks a lot! is there something similar for the body background?

**Comment by edy-ap** [comment]
You can use header template for customize the search bar

**Comment by serridavide** [comment]
No matter what I try I only managed to change the title color nothing more... Do you have an example with search bar Background changed that I can follow?



![Capture1](https://user-images.githubusercontent.com/72458567/101140181-e4bf8500-3612-11eb-91e0-a1d6a3493297.PNG)
![Capture2](https://user-images.githubusercontent.com/72458567/101140262-028cea00-3613-11eb-8f02-0dff2156080c.PNG)

**Comment by cristianofromagio** [comment]
@serridavide I think your issue now is more with styling Ionic components. Also from your screenshots you're styling `ion-toolbar` but you're using `ion-navbar` in the template (there is no `ion-navbar` on Ionic 4+).

**Comment by serridavide** [comment]
> @serridavide I think your issue now is more with styling Ionic components. Also from your screenshots you're styling `ion-toolbar` but you're using `ion-navbar` in the template (there is no `ion-navbar` on Ionic 4+).

I already successfully styled Ionic components. that example was an already working Stackblitz taken directly from the documentation of ionic-selectable.  `ion-toolbar` is present in the template (you could check by using chrome developer tools). If you look at the first image i did try to style the  `ion-navbar` anyway. The issue is that the `ionic-selectable` component wraps everything that goes into himself and make all attempts to style direct tags impossible. This issue is about asking if there is a direct way to style components wrapped in the `ionic-selectable` or if there is some other way to do it. I hope my explanation made it easier to understand what i'm looking for.

**Comment by cristianofromagio** [comment]
Oh now I see. Found this stackblitz too. It's folder structure is kind of odd. Maybe it was a demo only setup? Anyway, you usually override Ionic styles using a global css stylesheet (not on a "component scoped" stylesheet, like our stackblitz), be it `global.css|scss`, `app.css|scss` or whatever it is named in your project.

**Comment by serridavide** [comment]
> Oh now I see. Found this stackblitz too. It's folder structure is kind of odd. Maybe it was a demo only setup? Anyway, you usually override Ionic styles using a global css stylesheet (not on a "component scoped" stylesheet, like our stackblitz), be it `global.css|scss`, `app.css|scss` or whatever it is named in your project.

Yes, the issue is that global method change the styling for the entire application. But as I specified in the issue I need to style only that component because my application is divided in multiple sections with different styling in each one of them.

**Comment by edy-ap** [comment]
You can use header template for customize the search bar, toggle "canSearch" to false, and in header template include your own search bar, you must implement logic filter, an use this methods:


https://github.com/eakoriakin/ionic-selectable/wiki#startsearch
https://github.com/eakoriakin/ionic-selectable/wiki#endsearch

**Comment by DevForAll-Loic** [comment]
> > @serridavide I think your issue now is more with styling Ionic components. Also from your screenshots you're styling `ion-toolbar` but you're using `ion-navbar` in the template (there is no `ion-navbar` on Ionic 4+).
> 
> I already successfully styled Ionic components. that example was an already working Stackblitz taken directly from the documentation of ionic-selectable. `ion-toolbar` is present in the template (you could check by using chrome developer tools). If you look at the first image i did try to style the `ion-navbar` anyway. The issue is that the `ionic-selectable` component wraps everything that goes into himself and make all attempts to style direct tags impossible. This issue is about asking if there is a direct way to style components wrapped in the `ionic-selectable` or if there is some other way to do it. I hope my explanation made it easier to understand what i'm looking for.

UP ! Using ng-template to customize Searchbar just doesnt work. Also, custom CSS from .scss files are just ignored, and using ng-template only work for the navbar but nothing work for Searchbar.

**Comment by sebafra** [comment]
> You can use header template for customize the search bar, toggle "canSearch" to false, and in header template include your own search bar, you must implement logic filter, an use this methods:
> 
> https://github.com/eakoriakin/ionic-selectable/wiki#startsearch https://github.com/eakoriakin/ionic-selectable/wiki#endsearch

Do you have an example of this implementation? I can´t make it work

**Comment by iamphedz** [comment]
hello. has anyone found a solution on this? i have created a standalone component with ionic-selectable on it. but someshow the custom header and footer template using <ng-template> seems to not working.
