### ISSUE TITLE
onClose not firing when the inner modal is directly dismissed with ModalController

### ISSUE THREAD

**Issue by Artaud** [ionic-selectable/ionic-selectable#319]
Description: 
When using Ionic ModalController.getTop() to be able to generically dismiss any ion-modal that is currently on the screen, IonicSelectable will not fire onClose() event when the modal is dismissed by calling dismiss().

````
this.modalCtrl.getTop()
  .then(modal => {
    if (modal) {
      modal.dismiss()
    }
})
````

Use case:
I'm using it for a canDeactivate guard in Angular, so that I can bind the browser/mobile back button to dismissing any modal that is currently on the screen.

Please let me know what you think about that, I'm open to do a PR after some discussion.

**Comment by edy-ap** [comment]
Is a great feature, which is currently not implemented.

If you can send a PR, it would be great.
