### ISSUE TITLE
clearButtonText not show

### ISSUE THREAD

**Issue by RidClick** [ionic-selectable/ionic-selectable#320]
ionic v6.12.3

"@angular/core": "^10.2.3",
"ionic-selectable": "^4.7.1"

`<ionic-selectable 
[canClear]="true"
clearButtonText="Clean">
</ionic-selectable>`

Show a button without text.

**Comment by RidClick** [comment]
Any solution for this?

**Comment by edy-ap** [comment]
Can you show and example?

**Comment by RidClick** [comment]
I have found the real problem with this.
It turns out that in my application I need the footer with a background transparent and for some reason you have decided to put the text color for the html button not the ion-button with the css like

`
background: var(--ion-toolbar-color, var(--background));
color: var(--ion-toolbar-background, var (--color));
`

Which has driven me crazy for a couple of weeks until I found the problem.
I have solved the problem by changing the color of my toolbar.

`--ion-toolbar-background: var(--ion-background-color);`

I suppose the other option is to add a custom button that fires the clean event but I suppose the css problem would continue.
For my part I have understood the problem and you can close this issue.
