### ISSUE TITLE
It takes a lot time in Render the data

### ISSUE THREAD

**Issue by maniyarkj** [ionic-selectable/ionic-selectable#323]
I have used the ionic-selectable where I load the city list based on the state. I see that the API response is just within milli second, however, it takes 3-4 second sometimes even more than it takes to load the city list. The data length is hardly 250 records.

**Comment by edy-ap** [comment]
You can use VirtualScroll or InfiniteScroll

https://github.com/eakoriakin/ionic-selectable/wiki#hasvirtualscroll
https://github.com/eakoriakin/ionic-selectable/wiki#hasinfinitescroll

**Comment by maniyarkj** [comment]
Hi Avendano,

I have already tried both versions. but still, whenever the list grows, the
behaviour of control is not ok.

*Thanks & Regards,*
*Khilen*
