### ISSUE TITLE
Calling open() will not trigger onOpen emission

### ISSUE THREAD

**Issue by Artaud** [ionic-selectable/ionic-selectable#328]
Expected behaviour:
When calling open() on IonicSelectable, the onOpen event should be emitted.

Actual behaviour:
When calling open() on IonicSelectable, the onOpen event is not emitted.

Version used: 4.7.1

**Comment by vitordhers** [comment]
Had the sample problem. Grossly fixed by calling `this.onOpen()` inside the open callback function.

**Comment by edy-ap** [comment]
it will solved in Ionic Selectable v5(currently in alpha)
@ionic-selectable/core for Vanilla JS
@ionic-selectable/angular for Angular
