### ISSUE TITLE
Is possible change text from labels?

### ISSUE THREAD

**Issue by DanielHPassos** [ionic-selectable/ionic-selectable#331]
I'd like the change text that appears in labels when clicked in select box.

Print below
![image](https://user-images.githubusercontent.com/11998795/109426405-62095480-79cc-11eb-9f38-289c6347302a.png)

And, is possible set limit in multi select for N selections?

**Comment by benjamincreativedk** [comment]
Hi
You can change "Cancel" and many other things with the [template feature](https://github.com/eakoriakin/ionic-selectable/wiki#templates) (ionicSelectableCloseButtonTemplate) But I can't find a way to change "Search".. About the limit in selections check: [Min/max selection](https://github.com/eakoriakin/ionic-selectable/wiki#minmax-selection)

**Comment by DanielHPassos** [comment]
Hi,

Other issue...
Is possible edit css from component? I tried but not works...

![image](https://user-images.githubusercontent.com/11998795/111918976-5c9ca880-8a66-11eb-9753-abe05f5949ff.png)

**Comment by edy-ap** [comment]
it will solved in Ionic Selectable v5(currently in alpha) : with 'searchPlaceholder' property
@ionic-selectable/core for Vanilla JS
@ionic-selectable/angular for Angular
