### ISSUE TITLE
Alpha 9 not working with Ionic 5

### ISSUE THREAD

**Issue by viztastic** [ionic-selectable/ionic-selectable#338]
Hi, when I use the getting started template, I endup with this (no errors in my console):

![image](https://user-images.githubusercontent.com/8556736/113504030-e07f8600-9578-11eb-9e36-4f0a734ed52d.png)

Inside my signin.html
```html
<ion-content>
	<ion-item>
		<ion-label text-wrap>
			Basic usage.
		</ion-label>
	</ion-item>
	<ion-item>
		<ion-label>Port</ion-label>
		<ionic-selectable item-content [(ngModel)]="port" itemValueField="id" itemTextField="name" [items]="ports" [canSearch]="true"
		 (onChange)="portChange($event)">
		</ionic-selectable>
	</ion-item>
</ion-content>
```

signin.ts

```typescript
@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.scss'],
})
export class SigninComponent {

  ports: Port[];
  port: Port;

  constructor() {
    this.ports = [
      { id: 1, name: 'Tokai' },
      { id: 2, name: 'Vladivostok' },
      { id: 3, name: 'Navlakhi' }
    ];
  }

  portChange(event: {
    component: IonicSelectableComponent,
    value: any
  }) {
    console.log('port:', event.value);
  }

}


```

Is there a different way to bootstrap ion-selectable inside ionic v5?

I'm trying to re-create https://github.com/webcat12345/ngx-intl-tel-input/ in an ionic friendly way using ion-selectable.

Any help is much appreciated!

**Comment by stefanhk31** [comment]
I'm getting the exact same issue on v5.

**Comment by edy-ap** [comment]
Thanks for reporting, is an doc issue: In AppModule you add 'IonicSelectableModule.forRoot()' rather than 'IonicSelectableModule'

```ts
@NgModule({
  imports: [
    IonicSelectableModule.forRoot()
  ]
})
export class AppModule { }
```
let me know if it worked for you.

**Comment by DevForAll-Loic** [comment]
> Thanks for reporting, is an doc issue: In AppModule you add 'IonicSelectableModule.forRoot()' rather than 'IonicSelectableModule'
> 
> ```ts
> @NgModule({
>   imports: [
>     IonicSelectableModule.forRoot()
>   ]
> })
> export class AppModule { }
> ```
> 
> let me know if it worked for you.

Doesnt work. 
![Capture d’écran 2021-07-06 à 14 45 24](https://user-images.githubusercontent.com/54630306/124602158-dc5d5000-de68-11eb-9672-5479d3f2b8c1.png)
