### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by Path-A** [ionic-selectable/ionic-selectable#339]
Now that v5 alpha has React and Angular support, it would be great to add Vue so that all Ionic-supported frameworks are able to use ionic-selectable .

**Comment by Path-A** [comment]
Nevermind. It's core js support, not react.

**Comment by edy-ap** [comment]
yes in a future we will support react and vue

**Comment by boozedog** [comment]
> yes in a future we will support react and vue

Is Vue supported?
