### ISSUE TITLE
There is no way to change the color (bg-color) of specific ionic option with a condition

### ISSUE THREAD

**Issue by Pumayk26** [ionic-selectable/ionic-selectable#340]
I want to change the color of specific row. Anyone has any idea how to get this done..? I couldn't see any options in the doc... 

![Capture](https://user-images.githubusercontent.com/22075059/115201723-45a7af80-a113-11eb-8465-cd5a494ef262.PNG)

**Comment by edy-ap** [comment]
With https://github.com/ionic-selectable/ionic-selectable/wiki#item-template
