### ISSUE TITLE
[Feature Request] Search items with searchText using (starts with) instead of (includes)

### ISSUE THREAD

**Issue by Maged-Abdulrahman** [ionic-selectable/ionic-selectable#342]
Currently the default behavior of the search mechanism is that it searches the items with the (includes) technique.
Example: a list includes both 'Ford' and 'Benford', if I type 'Fo' as the search text, it'll get both of these two items. I only want Ford which the search text starts with.
Here's what I mean:

<img width="218" alt="Screen Shot 2021-04-21 at 10 28 19 AM" src="https://user-images.githubusercontent.com/51088598/115522390-5a5b8300-a28c-11eb-8be9-cdb60d1e6d03.png">

How can I do this? Can an attribute be added to set the search mechanism to be (starts with) instead of (includes)?
Thanks.

**Comment by edy-ap** [comment]
you can use
-  https://github.com/ionic-selectable/ionic-selectable/wiki#header-template,
- https://github.com/ionic-selectable/ionic-selectable/wiki#startsearch
- https://github.com/ionic-selectable/ionic-selectable/wiki#endsearch

for implement your own search logic

**Comment by Maged-Abdulrahman** [comment]
Thanks for your response.
I managed to get it done by the onSearch event.

For future reference, here's my solution that made it as dynamic as possible.

`onSearchChange(event: {
    component: IonicSelectableComponent,
    text: string
  }, filterArray, filterField) {
    let searchText = event.text.trim().toLowerCase();
    event.component.startSearch();
    event.component.items = this.filterItems(filterArray, searchText, filterField);
    event.component.endSearch();
  }

  filterItems(array: any[], searchText: string, filterField: any) {
    return array.filter(element => {
      return String(element[filterField]).toLowerCase().startsWith(searchText)
    });
  }`
