### ISSUE TITLE
Adding footer template disables the selection by click

### ISSUE THREAD

**Issue by harilal** [ionic-selectable/ionic-selectable#352]
Once Footer template added, the single selection will not happen by clicking the option. If the template is not added once the user clicks option will close the dropdown and selects the items. this functionality will not happen once footer template added

https://stackblitz.com/edit/ionic-selectable-basic-zuqb67?file=app/pages/home/home.html

**Comment by edy-ap** [comment]
Version 3.x is not maintained, please update to version 4.x or 5.x, please
