### ISSUE TITLE
Open modal via code

### ISSUE THREAD

**Issue by BossuytWannes** [ionic-selectable/ionic-selectable#354]
Is it possible to manually trigger the modal to open via code?

Version:     "@ionic-selectable/angular": "^5.0.0-alpha.13",

**Comment by Abaddon-88** [comment]
[https://github.com/ionic-selectable/ionic-selectable/wiki#open](url)

open()
Version added: 3.0.1, 4.0.0

Opens Modal.

Returns
Promise<void>
Promise that resolves when Modal has been opened.

Example
View:

<ionic-selectable
  #portComponent>
</ionic-selectable>
TypeScript:

@ViewChild('portComponent') portComponent: IonicSelectableComponent;

open() {
  this.portComponent.open();
}

**Comment by Abaddon-88** [comment]
![Bildschirmfoto 2021-08-04 um 17 25 58](https://user-images.githubusercontent.com/33458656/128208687-250425ff-7801-42b2-8ca4-461a57cbc358.png)
