### ISSUE TITLE
Cant open ionic-selectable on a modal ionic 5

### ISSUE THREAD

**Issue by Sebastian-Elstadt** [ionic-selectable/ionic-selectable#391]
When an ionic-selectable element is present on an ion-modal it will fail to open. Upon further inspection, the problem seems to stem from a "connectedCallback" function which calls "document.querySelector('ion-modal')". This querySelector function gets the wrong ion-modal, not the selectable.

**Comment by edy-ap** [comment]
Hi  i will check this

**Comment by edy-ap** [comment]
Hi this will be fixed in the next version, stay tuned.
