### ISSUE TITLE
How to search groups?

### ISSUE THREAD

**Issue by Hedronmx** [ionic-selectable/ionic-selectable#396]
How can i search through groups?

Lets say we have a food list and then the structure is like this

PASTAS
  spaghetti
  Lasagna
BURGERS
  Cheese burger
   Bacon burger

How can i search for Pastas and get spaghetti and lasagna as a result?? Thanks

**Comment by edy-ap** [comment]
Hi, you can use "onSearch" event to customize your search logic, https://stackblitz.com/edit/ionic-selectable-on-search?file=pages%2Fhome%2Fhome.html
