### ISSUE TITLE
Multiple values for itemTextField

### ISSUE THREAD

**Issue by stefanofinetti** [ionic-selectable/ionic-selectable#400]
Hello,

i'd like to point out that this is not a bug, ionic-selectable is working just fine in my app.

What i'd like to have is the possibility to show 2 fields of a record in the itemTextField. I have a query that returns a list of people and in the db I have 2 separate fields for first and last name.
Once I select one of the records in the list, I'd like to see, as text field, a concatenation of last name and first name.
Is that possible somehow without manipulating the original record data (which I can't do because the db is not mine and I only have the Rest method to get the informations?)

Thanks.

**Comment by eakoriakin** [comment]
@stefanofinetti hi, I think what you a looking for are templates, particularly these two: [item template](https://github.com/ionic-selectable/ionic-selectable/wiki#item-template) and [value template](https://github.com/ionic-selectable/ionic-selectable/wiki#value-template).
