### ISSUE TITLE
confirm select when select an item

### ISSUE THREAD

**Issue by zeropy009** [ionic-selectable/ionic-selectable#401]
how can confirm an item when I click it before add it to selected list of ionic-selectable ?
I was try with :
onSelect(event: {
        component: IonicSelectableComponent,
        isSelected: boolean,
        item: Service
      }) {
        if (event.isSelected) {
            let userResult : boolean;
            userResult  = ..... // ask user to select it or not select
            event.isSelected = userResult;
        }
    }

But it not working, please help me
Thank you.

**Comment by eakoriakin** [comment]
Is this what you are looking for?
https://github.com/ionic-selectable/ionic-selectable/wiki#hasconfirmbutton

**Comment by zeropy009** [comment]
> Is this what you are looking for? https://github.com/ionic-selectable/ionic-selectable/wiki#hasconfirmbutton

my project isMultiple = "true" so hasConfirmButton always true. I just want check a condition when click item to control it to "selected" or "not selected"

**Comment by eakoriakin** [comment]
So what exactly do you want to happen when you click an item?

**Comment by zeropy009** [comment]
> So what exactly do you want to happen when you click an item?

I want to control its selection state according to my selection

**Comment by eakoriakin** [comment]
You can use `(onSelect)="onSelect($event)">` event and update a related item (sync its selection state) as shown below.

```
public onSelect(event): void {
  event.item.isSelected = event.isSelected;
}
```

Note that `item.isSelected` is a custom property of your item, you can call it what you like, whereas `event.isSelected` is a read-only property of the ionic-selectable event.

**Comment by eakoriakin** [comment]
Also, if you wish to exclude some items from the selection, but keep them visible in the list you can disable those items. Disabled items cannot be selected.
https://github.com/ionic-selectable/ionic-selectable/wiki#disableditems
![image](https://user-images.githubusercontent.com/2555923/205034223-314034d4-e088-40be-8ffc-c1ca610d1c40.png)

**Comment by zeropy009** [comment]
> `vent.isSelected` is a read-only property of the ionic-selectable event.

my project need check condition then ask user to confirm check or not check so can't disable it. Thank for help.

**Comment by eakoriakin** [comment]
Is the issue solved?

**Comment by zeropy009** [comment]
> Is the issue solved?

I think i must custom item-template no more choice, I don't know why event.isSelected  is a read-only property, it should can set value xD
